/*
 View: can not contain any data, but can contain the queries retrieve from data
        reusable, can expose only part of the table

 CREATE VIEW:
        CREATE VIEW VIEWNAME AS STATEMENT ;
 REPLACE VIEW:
        CREATE OR REPLACE VIEW VIEWNAME AS STATEMENT ;
 DROPPING VIEW:
        DROP VIEW VIEWNAME ;
 */

SELECT *
FROM EMPLOYEES ;

SELECT LAST_NAME||' '||FIRST_NAME AS "FULL NAME"
FROM EMPLOYEES ;

CREATE VIEW "EMPLOYEE INFO" AS SELECT LAST_NAME||' '||FIRST_NAME AS "FULL NAME"
FROM EMPLOYEES ;

SELECT * FROM "EMPLOYEE INFO";


SELECT LAST_NAME||' '||FIRST_NAME AS "FULL NAME",
       LOWER(EMAIL||'@CYBERTEK.COM') AS "EMAIL"
FROM EMPLOYEES ;

CREATE OR REPLACE VIEW "EMPLOYEE INFO" AS SELECT LAST_NAME||' '||FIRST_NAME AS "FULL NAME",
                                                 LOWER(EMAIL||'@CYBERTEK.COM') AS "EMAIL"
                                          FROM EMPLOYEES ;

SELECT * FROM "EMPLOYEE INFO";

DROP VIEW "EMPLOYEE INFO" ; -- IT IS GONE

/*
 CREATE TABLE:

    SYNTAX:
        CREATE TABLE TABLENAME(
            COLUMNNAME1 DATATYPE CONSTRAINT,
            COLUMNNAME2 DATATYPE CONSTRAINT
            );

 CONSTRAINT IS NOT MANDATORY

 */

CREATE TABLE ADDRESS(
  ADDRESS_ID INTEGER PRIMARY KEY ,
  ADDRESS VARCHAR(50) NOT NULL,
  PHONE INTEGER
);

