/*
 DROP TABLE: TO REMOVE EXISTING TABLE FROM THE DATABASE
    DROP TABLE TABLENAME;

 TRUNCATE TABLE: TRUNCATING WILL REMOVE ALL DATA FROM THE TABLE BUT NOT DELETE THE TABLE
        TRUNCATE TABLE TABLENAME;
 */
SELECT * FROM ADDRESS;
--SELECT * FROM SHOPPERS ;--DROPPED

--DROP TABLE SHOPPERS;

SELECT * FROM ADDRESS;

TRUNCATE TABLE ADDRESS;

SELECT * FROM ADDRESS;

DROP TABLE ADDRESS;

COMMIT WORK;

