
CREATE TABLE CLASSMATES(
  STUDENT_ID INTEGER PRIMARY KEY , --MUST BE UNIQUE AND CAN NOT BE NULL
  "FIRST NAME" VARCHAR(30),
  "LAST NAME" VARCHAR(30)
);



CREATE TABLE COWROKERS(
  EMPLOYEE_ID INTEGER PRIMARY KEY , -- MUST BE UNIQUE AND CAN NOT BE NULL
  "FIRST NAME" VARCHAR(30),
  "LAST NAME" VARCHAR(30),
  PERSONAL_ID INTEGER REFERENCES CLASSMATES(STUDENT_ID) -- FOREIGN KEY, DATA NEEDS TO BE MATCHED WITH THE REFERENCED PRIMARY KEY
-- FOREIGN KEY CAN BE DUPLICATED, CAN BE NULL
);

INSERT INTO COWROKERS VALUES(1, 'JOHN', 'ERIC', NULL) ; -- BECAUSE STUDENT_ID IS NOT SPECIFIED YET SO NULL

INSERT INTO CLASSMATES VALUES (1, 'AARON', 'DANIEL');

SELECT * FROM CLASSMATES ;

INSERT INTO COWROKERS VALUES(2, 'Jimmy', 'Rose', 1) ;

--INSERT INTO COWROKERS VALUES(3, 'Ahmet', 'Mamat', 2);
  -- FOREIGN KEY DATA IS NOT MATCHING WITH THE REFERENCED PRIMARY KEY'S DATA

SELECT * FROM CLASSMATES;
UPDATE CLASSMATES
SET STUDENT_ID=4
WHERE STUDENT_ID=1;

ALTER TABLE CLASSMATES DROP COLUMN STUDENT_ID ;
TRUNCATE TABLE CLASSMATES;


-- DROP THE FOREIGN KEY COUMN ONLY OR ENTIRE TABLE
ALTER  TABLE COWROKERS DROP COLUMN PERSONAL_ID ;

SELECT * FROM COWROKERS;

UPDATE CLASSMATES
SET STUDENT_ID=4
WHERE STUDENT_ID=1;

ALTER TABLE CLASSMATES DROP COLUMN STUDENT_ID ;
TRUNCATE TABLE CLASSMATES;

SELECT * FROM CLASSMATES;
DROP TABLE CLASSMATES;

COMMIT WORK;


