/*
 Text function: string manipulations
    1. concatenation operator: ||
    2. Concat(value1, value2):
    3. Upper(value):
    4. Lower(value):
    5. initcap(value):
    6. length(value):
    7. replace(columnName, oldValue, newValue):
    8. substr(columnName, beg index, end index):
    9. trim(value):
    ONLY USED FOR THE DISPLAY OPTION, DOES NOT MODIFY THE TABLE
 */

 --concatenation operator: ||
SELECT EMAIL || '@gmail.com'
FROM EMPLOYEES ;

SELECT FIRST_NAME || ' ' || LAST_NAME
FROM EMPLOYEES ;

--Concat(value1, value2):
SELECT CONCAT(EMAIL, '@gmail.com')
FROM EMPLOYEES ;

SELECT CONCAT( CONCAT(FIRST_NAME, ' '), LAST_NAME )
FROM EMPLOYEES ;

--Upper(value):
SELECT UPPER(FIRST_NAME)
FROM EMPLOYEES ;

--LOWER(VALUE):
SELECT LOWER(FIRST_NAME)
FROM EMPLOYEES ;

SELECT LOWER(UPPER(FIRST_NAME))
FROM EMPLOYEES;

--INITCAP(VALUE): DISPLAY FIRST LETTER CAPITAL
SELECT INITCAP(EMAIL)
FROM EMPLOYEES ;

SELECT EMAIL
FROM EMPLOYEES ;

--LENGTH(VALUE):
SELECT  FIRST_NAME, LENGTH(FIRST_NAME)
FROM EMPLOYEES ;

--REPLACE(COLUMNNAME, OLDVALUE, NEWVALUE)
SELECT REPLACE(FIRST_NAME, 'e', 'E')
FROM EMPLOYEES ;

--SUBSTR(COLUMNNAME, BEGININDEX, ENDINDEX)
SELECT SUBSTR(FIRST_NAME, 0,1)
FROM EMPLOYEES ;

SELECT SUBSTR(FIRST_NAME, 0, 1)||'.'||SUBSTR(LAST_NAME,0,1) AS "INITIAL FULL NAME"
FROM EMPLOYEES ;

SELECT CONCAT( CONCAT(SUBSTR(FIRST_NAME, 0, 1),'.'),SUBSTR(LAST_NAME,0,1)  )
FROM EMPLOYEES ;

--TRIM(VALUE):
SELECT FIRST_NAME
FROM EMPLOYEES ;

SELECT CONCAT('   ', FIRST_NAME)
FROM EMPLOYEES ;

SELECT TRIM( CONCAT('  ',FIRST_NAME) )
FROM EMPLOYEES ;

